Flashato/Controllers/FlashcardsController.cs
using Flashato.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Flashato.Controllers
{
    [RoutePrefix("flashcards")]
    public class FlashcardsController : Controller
    {
        // GET: Flashcards
        public ActionResult Add()
        {
            return View("Index");
        }

        [Route("{id:int}/edit")]
        public ActionResult EditCard(int id)
        {
            Flashcard card = new Flashcard { Id = id };
            return View("Index", card);
        }

        public ActionResult All()
        {
            return View();
        }

        public ActionResult Study()
        {
            return View();
        }
    }
}

Flashato/Controllers/HomeController.cs
using Flashato.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Flashato.Controllers
{
    [RoutePrefix("cards")]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Route("{id:int}/edit")]
        public ActionResult EditCard(int id)
        {
            Flashcard card = new Flashcard { Id = id };
            return View("Index", card);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Flashato/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Flashato/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Flashato/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = null;
}

<!DOCTYPE html>
<html data-ng-app="Flashato">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Flashato</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">
    <link href="~/Content/Styles/style.css" rel="stylesheet" />
</head>
<body data-ng-controller="landing as main">


    <div id="landing-container">
        <div id="nav-bar">

            @Html.ActionLink("New Card", "Add", "Flashcards")
            @Html.ActionLink("View All", "All", "Flashcards")
            @Html.ActionLink("Study", "Study", "Flashcards")
            <div id="nav-border"></div>
        </div>

        <div class="landing-content">
            <img src="~/Images/Flashato_Logo1 copy.png" />
            <h2>Where any idiot can become a genius</h2>
            <a href="/flashcards/add" class="main-button">Get Started</a>
        </div>
    </div>

    <div id="bar1">
        <div class="feature-container">
            <div class="svg-wrap">
                <svg version="1.1" id="Capa_1" viewBox="0 0 60 60" style="0 0 60 60;">
                    <path class="glasses" d="M59,28h-2.18c-0.951-5.666-5.85-10-11.748-10c-5.822,0-10.696,4.119-11.825,9.579c-0.971-0.814-2.079-1.246-3.247-1.246
	    c-1.167,0-2.274,0.432-3.245,1.245C25.639,22.118,20.825,18,15.072,18C8.756,18,3.565,22.851,3.051,29H1c-0.553,0-1,0.448-1,1
	    s0.447,1,1,1h2.051c0.514,6.149,5.705,11,12.021,11c6.467,0,11.736-5.207,11.911-11.671c0.853-1.285,1.915-1.996,3.017-1.996
	    c1.102,0,2.164,0.712,3.017,1.996C33.195,36.793,38.528,42,45.072,42C51.649,42,57,36.617,57,30h2c0.553,0,1-0.448,1-1
	    S59.553,28,59,28z M15.072,40C9.519,40,5,35.514,5,30s4.519-10,10.072-10C20.64,20,25,24.393,25,30S20.64,40,15.072,40z M45.072,40
	    C39.519,40,35,35.514,35,30s4.519-10,10.072-10C50.64,20,55,24.393,55,30S50.64,40,45.072,40z" />
                </svg>
            </div>
            <h3>Smart People Wear These!</h3>
        </div>

        <div class="feature-container">
            <div class="svg-wrap">
                <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                     viewBox="0 0 54 54" style="enable-background:new 0 0 54 54;" xml:space="preserve">
                <path d="M27,8c-9.374,0-17,7.626-17,17c0,7.112,4.391,13.412,11,15.9V50c0,0.553,0.447,1,1,1h1v2c0,0.553,0.447,1,1,1h6
		c0.553,0,1-0.447,1-1v-2h1c0.553,0,1-0.447,1-1v-9.1c6.609-2.488,11-8.788,11-15.9C44,15.626,36.374,8,27,8z M30,49
		c-0.553,0-1,0.447-1,1v2h-4v-2c0-0.553-0.447-1-1-1h-1v-5h8v5H30z M31.688,39.242C31.277,39.377,31,39.761,31,40.192V42h-8v-1.808
		c0-0.432-0.277-0.815-0.688-0.95C16.145,37.214,12,31.49,12,25c0-8.271,6.729-15,15-15s15,6.729,15,15
		C42,31.49,37.855,37.214,31.688,39.242z" />
                <path d="M27,6c0.553,0,1-0.447,1-1V1c0-0.553-0.447-1-1-1s-1,0.447-1,1v4C26,5.553,26.447,6,27,6z" />
                <path d="M51,24h-4c-0.553,0-1,0.447-1,1s0.447,1,1,1h4c0.553,0,1-0.447,1-1S51.553,24,51,24z" />
                <path d="M7,24H3c-0.553,0-1,0.447-1,1s0.447,1,1,1h4c0.553,0,1-0.447,1-1S7.553,24,7,24z" />
                <path d="M43.264,7.322l-2.828,2.828c-0.391,0.391-0.391,1.023,0,1.414c0.195,0.195,0.451,0.293,0.707,0.293
		s0.512-0.098,0.707-0.293l2.828-2.828c0.391-0.391,0.391-1.023,0-1.414S43.654,6.932,43.264,7.322z" />
                <path d="M12.15,38.436l-2.828,2.828c-0.391,0.391-0.391,1.023,0,1.414c0.195,0.195,0.451,0.293,0.707,0.293
		s0.512-0.098,0.707-0.293l2.828-2.828c0.391-0.391,0.391-1.023,0-1.414S12.541,38.045,12.15,38.436z" />
                <path d="M41.85,38.436c-0.391-0.391-1.023-0.391-1.414,0s-0.391,1.023,0,1.414l2.828,2.828c0.195,0.195,0.451,0.293,0.707,0.293
		s0.512-0.098,0.707-0.293c0.391-0.391,0.391-1.023,0-1.414L41.85,38.436z" />
                <path d="M12.15,11.564c0.195,0.195,0.451,0.293,0.707,0.293s0.512-0.098,0.707-0.293c0.391-0.391,0.391-1.023,0-1.414l-2.828-2.828
		c-0.391-0.391-1.023-0.391-1.414,0s-0.391,1.023,0,1.414L12.15,11.564z" />
                <path d="M27,13c-6.617,0-12,5.383-12,12c0,0.553,0.447,1,1,1s1-0.447,1-1c0-5.514,4.486-10,10-10c0.553,0,1-0.447,1-1
		S27.553,13,27,13z" />
        </svg>
            </div>
            <h3>Learn how to use a Lightbulb!</h3>
        </div>

        <div class="feature-container">
            <div class="svg-wrap">
                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                     viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<g>
                <g>
                <path d="M453.958,214.331c-3.531-26.577-16.079-51.055-35.8-69.556c-21.625-20.286-49.874-31.457-79.542-31.457
			c-4.588,0-9.318,0.322-14.343,0.979c-22.641-17.281-50.542-26.745-79.134-26.745c-30.593,0-60.141,10.807-83.651,30.513
			c-35.004,2.468-68.221,16.911-93.913,40.916c-25.706,24.017-42.375,56.158-47.176,90.821C7.219,266.12,0,286.428,0,307.378
			c0,49.209,39.105,89.621,87.876,91.676c25.144,16.624,54.271,25.394,84.459,25.394c37.963,0,74.151-13.934,102.41-39.328h96.687
			c13.997,7.673,29.676,11.714,45.549,11.714c52.394,0,95.019-42.625,95.019-95.019C512,263.371,488.963,229.09,453.958,214.331z
			 M416.982,374.404c-12.902,0-25.65-3.51-36.869-10.151c-1.729-1.024-3.703-1.565-5.713-1.565h-84.242
			c2.38-6.154,3.638-12.75,3.638-19.543c0-14.462-5.638-28.065-15.876-38.303c-4.162-4.16-10.907-4.16-15.069,0
			c-4.161,4.161-4.161,10.908,0,15.068c6.213,6.213,9.636,14.464,9.636,23.236c0,7.738-2.667,15.071-7.562,20.958
			c-0.83,0.46-1.608,1.016-2.306,1.681c-24.529,23.366-56.593,36.234-90.284,36.234c-26.74,0-52.505-8.063-74.511-23.315
			c-0.299-0.208-0.611-0.394-0.927-0.571c-14.549-16.78-13.864-42.278,2.08-58.221c4.161-4.161,4.161-10.907,0-15.068
			c-4.162-4.16-10.907-4.16-15.069,0c-18.385,18.385-23.221,45.25-14.546,68.115c-27.255-9.357-46.932-35.247-46.932-65.581
			c0-16.695,6.083-32.859,17.128-45.517c1.492-1.709,2.429-3.832,2.689-6.086c3.547-30.678,17.979-59.232,40.639-80.402
			c17.293-16.157,38.579-27.233,61.457-32.233c-2.707,7.035-4.14,14.574-4.14,22.334c0,16.597,6.471,32.21,18.22,43.959
			c2.08,2.08,4.807,3.12,7.534,3.12s5.453-1.041,7.534-3.12c4.161-4.161,4.161-10.908,0-15.069
			c-7.726-7.725-11.98-17.985-11.98-28.891c0-9.896,3.514-19.255,9.935-26.676c0.691-0.39,1.348-0.847,1.948-1.382
			c19.859-17.69,45.337-27.433,71.743-27.433c19.066,0,37.752,5.092,54.097,14.54c-13.887,9.918-22.038,26.961-19.73,45.041
			c0.688,5.38,5.272,9.306,10.556,9.306c0.449,0,0.905-0.028,1.363-0.086c5.837-0.746,9.965-6.082,9.22-11.918
			c-1.854-14.518,8.448-27.838,22.967-29.693c0.545-0.07,1.07-0.192,1.584-0.339c4.811-0.716,9.238-1.087,13.421-1.087
			c44.457,0,82.394,31.462,91.732,73.781c-21.863-0.091-42.563,13.145-50.856,34.735c-2.111,5.493,0.631,11.656,6.126,13.767
			c1.256,0.483,2.547,0.712,3.818,0.712c4.282,0,8.32-2.601,9.948-6.838c5.905-15.373,22.175-23.772,37.792-20.297
			c0.847,0.581,1.774,1.061,2.78,1.397c29.676,9.906,49.615,37.559,49.615,68.81C489.57,341.841,457.007,374.404,416.982,374.404z" />
	</g>
</g>
<g>
                <g>
                <path d="M438.895,287.481c-21.707,0-39.367,17.659-39.367,39.367c0,5.885,4.77,10.654,10.654,10.654s10.654-4.77,10.654-10.654
			c0-9.958,8.101-18.059,18.059-18.059c5.885,0,10.654-4.77,10.654-10.654S444.78,287.481,438.895,287.481z" />
	</g>
</g>
<g>
                <g>
                <path d="M193.566,274.711c-25.78,0-46.754,20.973-46.754,46.753c0,5.885,4.77,10.654,10.654,10.654
			c5.885,0,10.654-4.77,10.654-10.654c0-14.03,11.415-25.445,25.445-25.445c5.885,0,10.654-4.77,10.654-10.654
			C204.221,279.481,199.451,274.711,193.566,274.711z" />
	</g>
</g>
<g>
                <g>
                <path d="M320.932,240.482c-12.608-28.065-45.698-40.641-73.763-28.034c-5.368,2.41-7.764,8.718-5.353,14.085
			c2.41,5.366,8.714,7.764,14.085,5.353c17.348-7.789,37.802-0.02,45.593,17.328c1.774,3.951,5.658,6.291,9.726,6.291
			c1.459,0,2.942-0.302,4.359-0.938C320.947,252.156,323.344,245.851,320.932,240.482z" />
</svg>
            </div>
            <h3>On average, Flashato users report having one of these</h3>
        </div>

    </div>

    <div class="divider">
        
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")

</body>
</html>

<script type="text/javascript">
    (function () {
        "use strict";

        angular.module('Flashato', []).controller('landing', LandingController);

        LandingController.$inject = ['$scope'];

        function LandingController($scope) {
            var vm = this;
            vm.$scope = $scope;
        }
    })();

</script>